"""Planner agent — expands a 1–4 sentence idea into a full product spec.

Writes: artifacts/plan/PRODUCT_SPEC.md  +  artifacts/plan/sprints.json
"""
from __future__ import annotations

import json

from . import _context as ctxmod
from ._context import RunContext, validate_json_file
from ._runtime import AgentResult, ensure_ok, run_claude

SYSTEM_PROMPT = (ctxmod.HARNESS_DIR / "prompts" / "planner_system.md")

ALLOWED_TOOLS = ["Read", "Glob", "Grep", "Write", "Edit", "Skill", "WebFetch", "TodoWrite"]


def run_planner(ctx: RunContext, user_prompt: str) -> AgentResult:
    ctx.ensure_dirs()
    if ctx.dry_run:
        return _dry_run(ctx, user_prompt)

    task = f"""You are the PLANNER. Expand this idea into a full LANDING-PAGE specification.

USER IDEA:
{user_prompt}

First read criteria/landing_playbook.md. Then write BOTH files (absolute paths):
1. {ctx.product_spec_md}   (human-readable, the structure in your system prompt)
2. {ctx.sprints_json}      (machine-readable; MUST validate against
   {ctx.schemas_dir / 'product_spec.schema.json'} — 4–5 sprints, ≥3 section-features,
   tech_stack.backend/ai as "None" unless the brief needs them)

The sprints.json is authoritative — the orchestrator reads it. Make the two files
consistent. Apply the frontend-design skill to the design language. Then stop."""

    result = run_claude(
        ctx,
        role="planner",
        system_prompt=SYSTEM_PROMPT.read_text(encoding="utf-8"),
        task_prompt=task,
        model=ctx.config["models"]["planner"],
        cwd=ctx.harness_dir,
        allowed_tools=ALLOWED_TOOLS,
        # criteria/ is included so the planner can read landing_playbook.md (stack, sections,
        # CWV, anti-template bar) — generator/evaluator already get it; the planner needs it
        # too to spec against the same standard.
        add_dirs=[ctx.artifacts_dir, ctx.schemas_dir, ctx.harness_dir / "criteria"],
        permission_mode="acceptEdits",
    )
    ensure_ok(result, "planner")
    # hard gate: the spec must exist and validate or the whole run is meaningless
    validate_json_file(ctx, ctx.sprints_json, "product_spec.schema.json")
    return result


def _dry_run(ctx: RunContext, user_prompt: str) -> AgentResult:
    name = user_prompt.strip().rstrip(".") or "Demo Landing Page"
    spec = {
        "overview": f"A dry-run landing-page spec for: {name}. Generated by the harness in "
        "dry-run mode to exercise the orchestration loop without spawning agents.",
        "design_language": {
            "color_palette": {
                "primary": "oklch(62% 0.19 256)",
                "secondary": "oklch(72% 0.12 200)",
                "accent": "oklch(78% 0.17 85)",
                "background": "oklch(98% 0.01 256)",
                "surface": "oklch(100% 0 0)",
            },
            "typography": {
                "heading_font": "Fraunces",
                "body_font": "Inter",
                "tone": "editorial, confident",
            },
            "ui_mood": ["editorial", "high-contrast", "warm"],
            "key_ui_patterns": ["full-bleed hero", "bento feature grid", "sticky CTA"],
        },
        "features": [
            {"id": "F1", "title": "Hero section", "user_story": "As a visitor, I want to instantly grasp the offer and act."},
            {"id": "F2", "title": "Features & social proof", "user_story": "As a visitor, I want to see benefits and trust signals."},
            {"id": "F3", "title": "FAQ & final CTA", "user_story": "As a visitor, I want my questions answered and a clear next step."},
        ],
        "sprints": [
            {"number": 1, "name": "Hero + shell + tokens", "deliverables": ["Next.js scaffold", "design tokens", "above-the-fold hero"], "success_criteria": ["page boots at :3000", "design tokens applied", "primary CTA present"]},
            {"number": 2, "name": "Content sections", "deliverables": ["features/benefits", "social proof", "FAQ", "footer"], "success_criteria": ["all sections render with real copy", "FAQ accordion works"]},
            {"number": 3, "name": "Responsive + motion", "deliverables": ["all breakpoints", "scroll/hover motion"], "success_criteria": ["no overflow at 320px", "reduced-motion honored"]},
            {"number": 4, "name": "A11y + performance + SEO", "deliverables": ["WCAG AA pass", "CWV pass", "metadata/OG"], "success_criteria": ["keyboard operable", "LCP < 2.5s", "title/description/OG present"]},
        ],
        "ai_integration_points": [],
        "tech_stack": {
            "frontend": "Next.js (App Router) + TypeScript + Tailwind (customized)",
            "backend": "None — static export",
            "ai": "None",
        },
    }
    ctx.sprints_json.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    md = [f"## Overview\n{spec['overview']}\n", "## Design Language"]
    cp = spec["design_language"]["color_palette"]
    md.append(f"- Color palette: {', '.join(f'{k} {v}' for k, v in cp.items())}")
    ty = spec["design_language"]["typography"]
    md.append(f"- Typography: {ty['heading_font']} / {ty['body_font']} ({ty['tone']})")
    md.append(f"- UI Mood: {', '.join(spec['design_language']['ui_mood'])}")
    md.append(f"- Key UI Patterns: {', '.join(spec['design_language']['key_ui_patterns'])}\n")
    md.append("## Features")
    for f in spec["features"]:
        md.append(f"{f['id']}. {f['title']} — {f['user_story']}")
    md.append("\n## Sprint Plan")
    for s in spec["sprints"]:
        md.append(f"Sprint {s['number']}: {s['name']} — {'; '.join(s['deliverables'])} — {'; '.join(s['success_criteria'])}")
    if spec.get("ai_integration_points"):
        md.append("\n## AI Integration Points")
        md += [f"- {p}" for p in spec["ai_integration_points"]]
    md.append("\n## Tech Stack")
    md.append(f"Frontend: {spec['tech_stack']['frontend']}")
    md.append(f"Backend: {spec['tech_stack']['backend']}")
    md.append(f"AI: {spec['tech_stack']['ai']}")
    ctx.product_spec_md.write_text("\n".join(md) + "\n", encoding="utf-8")
    validate_json_file(ctx, ctx.sprints_json, "product_spec.schema.json")
    return AgentResult(ok=True, text="[dry-run] spec written", cost_usd=0.0, num_turns=0, returncode=0, raw="")
