export {
  CategoryItemSchema,
  DifficultyItemSchema,
  CategoriesListResponseSchema,
  DifficultiesListResponseSchema,
  CreateCategoryRequestSchema,
  UpdateCategoryRequestSchema,
  CategoryResponseSchema,
  CreateDifficultyRequestSchema,
  UpdateDifficultyRequestSchema,
  DifficultyResponseSchema,
  type CategoryItem,
  type DifficultyItem,
  type CategoriesListResponse,
  type DifficultiesListResponse,
  type CreateCategoryRequest,
  type UpdateCategoryRequest,
  type CategoryResponse,
  type CreateDifficultyRequest,
  type UpdateDifficultyRequest,
  type DifficultyResponse,
} from '@/features/metadata/backend/schema';
