export {
  // Learner DTO
  AssignmentItemSchema,
  AssignmentListResponseSchema,
  AssignmentDetailResponseSchema,
  SubmitAssignmentRequestSchema,
  ResubmitAssignmentRequestSchema,
  SubmitAssignmentResponseSchema,
  type AssignmentItem,
  type AssignmentListResponse,
  type AssignmentDetailResponse,
  type SubmitAssignmentRequest,
  type ResubmitAssignmentRequest,
  type SubmitAssignmentResponse,

  // Instructor DTO
  CreateAssignmentRequestSchema,
  UpdateAssignmentRequestSchema,
  PublishAssignmentResponseSchema,
  CloseAssignmentResponseSchema,
  CreateAssignmentResponseSchema,
  UpdateAssignmentResponseSchema,
  MyAssignmentItemSchema,
  MyAssignmentsResponseSchema,
  SubmissionItemSchema,
  SubmissionsQuerySchema,
  AssignmentSubmissionsResponseSchema,
  type CreateAssignmentRequest,
  type UpdateAssignmentRequest,
  type PublishAssignmentResponse,
  type CloseAssignmentResponse,
  type CreateAssignmentResponse,
  type UpdateAssignmentResponse,
  type MyAssignmentItem,
  type MyAssignmentsResponse,
  type SubmissionItem,
  type SubmissionsQuery,
  type AssignmentSubmissionsResponse,

  // Grading DTO
  GradeSubmissionRequestSchema,
  RequestResubmissionRequestSchema,
  GradeSubmissionResponseSchema,
  RequestResubmissionResponseSchema,
  SubmissionDetailResponseSchema,
  type GradeSubmissionRequest,
  type RequestResubmissionRequest,
  type GradeSubmissionResponse,
  type RequestResubmissionResponse,
  type SubmissionDetailResponse,
} from '@/features/assignments/backend/schema';

export {
  getAssignmentStatusText,
  getAssignmentStatusColor,
  canPublish,
  canClose,
  type AssignmentStatus,
} from './assignment-status-utils';
