export {
  SeatSchema,
  SeatsResponseSchema,
  CreateBookingRequestSchema,
  CreateBookingResponseSchema,
  BookingDetailResponseSchema,
  LookupBookingsRequestSchema,
  LookupBookingsResponseSchema,
  BookingSummarySchema,
  CancelBookingRequestSchema,
  CancelBookingResponseSchema,
  type Seat,
  type SeatsResponse,
  type CreateBookingRequest,
  type CreateBookingResponse,
  type BookingDetailResponse,
  type LookupBookingsRequest,
  type LookupBookingsResponse,
  type BookingSummary,
  type CancelBookingRequest,
  type CancelBookingResponse,
} from '@/features/bookings/backend/schema';
