"""Planner agent — expands a 1–4 sentence idea into a full product spec.

Writes: artifacts/plan/PRODUCT_SPEC.md  +  artifacts/plan/sprints.json
"""
from __future__ import annotations

import json

from . import _context as ctxmod
from ._context import RunContext, validate_json_file
from ._runtime import AgentResult, run_claude

SYSTEM_PROMPT = (ctxmod.HARNESS_DIR / "prompts" / "planner_system.md")

ALLOWED_TOOLS = ["Read", "Glob", "Grep", "Write", "Edit", "Skill", "WebFetch", "TodoWrite"]


def run_planner(ctx: RunContext, user_prompt: str) -> AgentResult:
    ctx.ensure_dirs()
    if ctx.dry_run:
        return _dry_run(ctx, user_prompt)

    task = f"""You are the PLANNER. Expand this product idea into a full specification.

USER IDEA:
{user_prompt}

Write BOTH files (absolute paths):
1. {ctx.product_spec_md}   (human-readable, the structure in your system prompt)
2. {ctx.sprints_json}      (machine-readable; MUST validate against
   {ctx.schemas_dir / 'product_spec.schema.json'} — 4–8 sprints, ≥3 features)

The sprints.json is authoritative — the orchestrator reads it. Make the two files
consistent. Apply the frontend-design skill to the design language. Then stop."""

    result = run_claude(
        ctx,
        role="planner",
        system_prompt=SYSTEM_PROMPT.read_text(encoding="utf-8"),
        task_prompt=task,
        model=ctx.config["models"]["planner"],
        cwd=ctx.harness_dir,
        allowed_tools=ALLOWED_TOOLS,
        add_dirs=[ctx.artifacts_dir, ctx.schemas_dir],
        permission_mode="acceptEdits",
    )
    # hard gate: the spec must exist and validate or the whole run is meaningless
    validate_json_file(ctx, ctx.sprints_json, "product_spec.schema.json")
    return result


def _dry_run(ctx: RunContext, user_prompt: str) -> AgentResult:
    name = user_prompt.strip().rstrip(".") or "Demo App"
    spec = {
        "overview": f"A dry-run product spec for: {name}. Generated by the harness in "
        "dry-run mode to exercise the orchestration loop without spawning agents.",
        "design_language": {
            "color_palette": {
                "primary": "oklch(62% 0.19 256)",
                "secondary": "oklch(72% 0.12 200)",
                "accent": "oklch(78% 0.17 85)",
                "background": "oklch(98% 0.01 256)",
                "surface": "oklch(100% 0 0)",
            },
            "typography": {
                "heading_font": "Fraunces",
                "body_font": "Inter",
                "tone": "editorial, confident",
            },
            "ui_mood": ["clean", "editorial", "high-contrast"],
            "key_ui_patterns": ["bento grid", "sticky sidebar", "inline AI panel"],
        },
        "features": [
            {"id": "F1", "title": "Core CRUD", "user_story": "As a user, I want to manage records."},
            {"id": "F2", "title": "AI insights", "user_story": "As a user, I want AI-generated insights."},
            {"id": "F3", "title": "Dashboard", "user_story": "As a user, I want an at-a-glance overview."},
        ],
        "sprints": [
            {"number": 1, "name": "Foundation & shell", "deliverables": ["app scaffold", "design tokens"], "success_criteria": ["app boots", "design tokens applied"]},
            {"number": 2, "name": "Core CRUD", "deliverables": ["records API", "list/detail UI"], "success_criteria": ["create works", "list renders"]},
            {"number": 3, "name": "AI insights", "deliverables": ["Claude integration", "insights panel"], "success_criteria": ["AI returns insight", "panel renders"]},
            {"number": 4, "name": "Dashboard & polish", "deliverables": ["overview", "responsive pass"], "success_criteria": ["dashboard renders", "no overflow at 320px"]},
        ],
        "ai_integration_points": ["Insights generation via Claude API with tool-calling"],
        "tech_stack": {
            "frontend": "React 18 + Vite + TypeScript + Tailwind",
            "backend": "FastAPI + SQLAlchemy + SQLite",
            "ai": "Claude API (claude-sonnet-4-6)",
        },
    }
    ctx.sprints_json.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    md = [f"## Overview\n{spec['overview']}\n", "## Design Language"]
    cp = spec["design_language"]["color_palette"]
    md.append(f"- Color palette: {', '.join(f'{k} {v}' for k, v in cp.items())}")
    ty = spec["design_language"]["typography"]
    md.append(f"- Typography: {ty['heading_font']} / {ty['body_font']} ({ty['tone']})")
    md.append(f"- UI Mood: {', '.join(spec['design_language']['ui_mood'])}")
    md.append(f"- Key UI Patterns: {', '.join(spec['design_language']['key_ui_patterns'])}\n")
    md.append("## Features")
    for f in spec["features"]:
        md.append(f"{f['id']}. {f['title']} — {f['user_story']}")
    md.append("\n## Sprint Plan")
    for s in spec["sprints"]:
        md.append(f"Sprint {s['number']}: {s['name']} — {'; '.join(s['deliverables'])} — {'; '.join(s['success_criteria'])}")
    md.append("\n## AI Integration Points")
    md += [f"- {p}" for p in spec["ai_integration_points"]]
    md.append("\n## Tech Stack")
    md.append(f"Frontend: {spec['tech_stack']['frontend']}")
    md.append(f"Backend: {spec['tech_stack']['backend']}")
    md.append(f"AI: {spec['tech_stack']['ai']}")
    ctx.product_spec_md.write_text("\n".join(md) + "\n", encoding="utf-8")
    validate_json_file(ctx, ctx.sprints_json, "product_spec.schema.json")
    return AgentResult(ok=True, text="[dry-run] spec written", cost_usd=0.0, num_turns=0, returncode=0, raw="")
