#!/usr/bin/env python3
"""
2026-05-08 환경스캐닝 통합 리포트 → daily-scan JSON 변환 주입
InvestScan이 읽을 수 있도록 raw/ 폴더에 저장
"""
import json, re
from datetime import datetime
from pathlib import Path

DEST = Path("/Users/kylechoi/Desktop/Ai_works/Vibe-Practice/EnvironmentScan-system-main-v4-main/env-scanning/raw/daily-scan-2026-05-08.json")
SCAN_DATE = "2026-05-08"

# 통합 리포트 Top 20 신호를 직접 인코딩
signals = [
    {"id":"int-001","title":"North Korea Rejects NPT, Deploys Nuclear Warship & Seoul-Range Artillery","source":"WF4/NK News","category":"Geopolitics","description":"DPRK simultaneously rejected NPT, announced nuclear-armed warship deployment by mid-June 2026, forward-deployed 155mm howitzers targeting Seoul, and marched troops in Russia's Victory Day parade for first time. NPT rejection is structurally irreversible in short term.","url":"https://www.nknews.org","published_date":SCAN_DATE,"steep_category":"P","tags":["DPRK","nuclear","geopolitics","Korea","escalation"],"relevance_score":9.4},
    {"id":"int-002","title":"Iran-Hormuz Blockade Triggers Asian Agricultural Crisis — 2027 Food Shock Imminent","source":"WF4/Washington Post","category":"Macro","description":"Fertilizer prices up 180% since Hormuz blockade. Iran accounts for 20% of Asia's fertilizer feedstock. 2027 food price spike is now locked in. Market-reality divergence (stocks at record highs) creates pre-shock conditions.","url":"https://www.washingtonpost.com","published_date":SCAN_DATE,"steep_category":"E","tags":["Iran","food security","fertilizer","commodities","supply chain"],"relevance_score":9.3},
    {"id":"int-003","title":"China PLA Command Instability — Xi Loses Faith in Generals During Peak Tension","source":"WF4/New York Times","category":"Geopolitics","description":"Xi Jinping dramatically lost faith in senior PLA generals. Multiple senior officers purged. Restructuring toward loyal technocrats during Taiwan Strait tensions and Iran war period simultaneously creates dangerous miscalculation window.","url":"https://www.nytimes.com","published_date":SCAN_DATE,"steep_category":"P","tags":["China","PLA","Xi Jinping","geopolitics","Taiwan"],"relevance_score":9.2},
    {"id":"int-004","title":"NATO First Response to Deep-Sea Cable Sabotage — Hybrid Warfare Threshold Crossed","source":"WF4/Wall Street Journal","category":"Geopolitics","description":"NATO triggered first-ever coordinated response to suspected deep-sea cable sabotage. Article 5 deliberations underway. Russia primary suspect. Establishes new precedent for hybrid warfare thresholds.","url":"https://www.wsj.com","published_date":SCAN_DATE,"steep_category":"P","tags":["NATO","hybrid warfare","infrastructure","Russia","Article 5"],"relevance_score":9.1},
    {"id":"int-005","title":"DPRK-Russia Alliance Institutionalized — Red Square Parade","source":"WF4/NK News","category":"Geopolitics","description":"North Korean soldiers marched in Russia's Red Square Victory Day parade for first time in history. Putin secretly awarded DPRK generals commanding troops in Kursk battle. Formalizes new geopolitical bloc with nuclear implications.","url":"https://www.nknews.org","published_date":SCAN_DATE,"steep_category":"P","tags":["DPRK","Russia","military alliance","geopolitics"],"relevance_score":9.0},
    {"id":"int-006","title":"Amazon Ecosystem Tipping Point — Dieback Could Begin by 2040s","source":"WF1/Mongabay","category":"Environment","description":"New integrated modeling finds combined deforestation and climate warming have superlinear interaction effects. Amazon could begin savannification a full decade earlier than IPCC 2050 estimates. 90 billion tonnes CO2 release risk.","url":"https://news.mongabay.com","published_date":SCAN_DATE,"steep_category":"E_env","tags":["Amazon","climate","tipping point","carbon","environment"],"relevance_score":8.3},
    {"id":"int-007","title":"South Korea Defense Minister Emergency US Visit — OPCON Transfer and Hormuz Deployment","source":"WF3/Naver News","category":"Korea","description":"Defense Minister made unannounced emergency visit to Washington DC. Agenda: wartime OPCON transfer timeline and potential Korean naval forces deployment to Strait of Hormuz.","url":"https://news.naver.com","published_date":SCAN_DATE,"steep_category":"P","tags":["Korea","OPCON","military","US alliance","Hormuz"],"relevance_score":8.4},
    {"id":"int-008","title":"Hantavirus Multi-Country Outbreak — WHO Emergency Response, 12+ Nations Affected","source":"WF4/AP News","category":"Health","description":"WHO Director-General personally overseeing evacuation of MV Hondius cruise ship. Cases confirmed across 12+ countries. Hantavirus has 30-40% mortality rate in severe cases. Critical question: human-to-human transmission?","url":"https://apnews.com","published_date":SCAN_DATE,"steep_category":"S","tags":["hantavirus","pandemic risk","WHO","public health"],"relevance_score":8.9},
    {"id":"int-009","title":"Korean Government Emergency Consultation on Glasswing Quantum Computing Threat","source":"WF3/Naver IT","category":"Technology","description":"Korean government convened emergency meeting on quantum computing project codenamed Glasswing. Emergency format implies urgency beyond routine planning. RSA-2048 encryption may be at risk if adversary achieves quantum capability.","url":"https://news.naver.com","published_date":SCAN_DATE,"steep_category":"T","tags":["quantum computing","cryptography","cybersecurity","Korea","post-quantum"],"relevance_score":8.9},
    {"id":"int-010","title":"Autonomous Adversary — LLM Agents Capable of APT-Level Cyberattacks","source":"WF2/arXiv:2605.06486","category":"Technology","description":"Language Model Agents demonstrated capable of autonomously orchestrating APT attack sequences including lateral movement. First empirical proof of AI-autonomous full attack chain execution. Cybersecurity paradigm shift within 12-18 months.","url":"https://arxiv.org/abs/2605.06486","published_date":SCAN_DATE,"steep_category":"T","tags":["AI","cybersecurity","LLM","APT","autonomous attack"],"relevance_score":9.0},
    {"id":"int-011","title":"AI Security at Scale — Mythos Identifies 271 Real Mozilla Vulnerabilities","source":"WF1/Ars Technica","category":"Technology","description":"AI security model Mythos found 271 real vulnerabilities in Mozilla codebase with <1% false positive rate. AI-driven code auditing now production-ready. Enterprise security teams will rapidly adopt.","url":"https://arstechnica.com","published_date":SCAN_DATE,"steep_category":"T","tags":["AI security","Mozilla","vulnerability","cybersecurity","enterprise"],"relevance_score":8.1},
    {"id":"int-012","title":"UK Renewables Save £1.7bn from Iran War Gas Price Shock","source":"WF1/Carbon Brief","category":"Energy","description":"UK wind and solar generation prevented £1.7 billion in gas import costs since Iran war began. Energy security argument reshaping global renewable policy. National security ministries becoming primary renewable energy drivers.","url":"https://www.carbonbrief.org","published_date":SCAN_DATE,"steep_category":"E_env","tags":["renewable energy","UK","energy security","Iran","gas prices"],"relevance_score":8.1},
    {"id":"int-013","title":"Apple to Source Chips from Intel — Trump Administration Reshapes Semiconductor Supply Chain","source":"WF3/Naver IT","category":"Semiconductors","description":"Apple will source chip production from Intel following Trump administration persuasion to support US-based semiconductor manufacturing. Significant shift from TSMC/Samsung. Redirects billions in chip orders.","url":"https://news.naver.com","published_date":SCAN_DATE,"steep_category":"T","tags":["Apple","Intel","TSMC","Samsung","semiconductor","supply chain","US policy"],"relevance_score":8.7},
    {"id":"int-014","title":"DHS DNA Surveillance Database for ICE Critics — Landmark Civil Liberties Lawsuit","source":"WF1/Ars Technica","category":"Governance","description":"DHS proposed DNA database targeting individuals who publicly oppose ICE enforcement activities. ACLU, EFF filed federal lawsuit. Qualitatively different threshold from prior surveillance programs — combining DNA biometrics with political opinion tracking.","url":"https://arstechnica.com","published_date":SCAN_DATE,"steep_category":"P","tags":["DHS","surveillance","civil liberties","biometrics","US policy"],"relevance_score":8.0},
    {"id":"int-015","title":"ASEAN+3 Cross-Border Payment Connectivity — Dollar-Alternative Architecture Maturing","source":"WF1/AMRO Asia","category":"Finance","description":"ASEAN+3 regional payment system achieves real-time multilateral settlement. 8 currencies now directly tradable without USD intermediation. $2.4T annual volume (3x increase since 2024). De-dollarization accelerating.","url":"https://www.amro-asia.org","published_date":SCAN_DATE,"steep_category":"E","tags":["ASEAN","de-dollarization","payments","USD","Southeast Asia"],"relevance_score":7.5},
    {"id":"int-016","title":"India Becomes New Supply Chain Hub — Record FDI","source":"WF1/Project Syndicate","category":"Macro","description":"India FDI inflows $89B record in 2025. Apple manufacturing in India 25% of global iPhone production (up from 7% in 2022). India-EU FTA reached in principle. Primary beneficiary of US-China decoupling.","url":"https://www.project-syndicate.org","published_date":SCAN_DATE,"steep_category":"E","tags":["India","FDI","supply chain","China decoupling","manufacturing"],"relevance_score":7.3},
    {"id":"int-017","title":"Korean Demographic Care Collapse — Over Half of Grandparents Involuntary Caregivers","source":"WF3/Naver News","category":"Korea","description":"Survey: over 50% of Korean grandparents care for grandchildren against their will. TFR 0.72. Informal care worth 30T won annually. Tipping point ORANGE — policy intervention window 5-10 years.","url":"https://news.naver.com","published_date":SCAN_DATE,"steep_category":"S","tags":["Korea","demographics","aging","fertility rate","social policy"],"relevance_score":8.5},
    {"id":"int-018","title":"Germany Military Rise — Structural Rearmament Risk","source":"WF1/ECFR","category":"Geopolitics","description":"Germany defense budget 95B EUR in 2026, up 83% in 2 years. 5th-generation domestic fighter program announced. ECFR warns rapid German rearmament without EU integration framework risks historical errors.","url":"https://ecfr.eu","published_date":SCAN_DATE,"steep_category":"P","tags":["Germany","NATO","rearmament","Europe","defense spending"],"relevance_score":7.5},
    {"id":"int-019","title":"LLM Safety Without Benchmarks — Direct EU AI Act Compliance Application","source":"WF2/arXiv:2605.06652","category":"Technology","description":"New formal framework for comparing LLM safety without labeled benchmarks. Directly applicable to EU AI Act. EU AI Act full implementation H2 2026 will drive rapid adoption.","url":"https://arxiv.org/abs/2605.06652","published_date":SCAN_DATE,"steep_category":"T","tags":["AI governance","EU AI Act","LLM safety","compliance","regulation"],"relevance_score":7.6},
    {"id":"int-020","title":"White House Systematic Strategy to Undermine Scientific Advisory Bodies","source":"WF1/Genetic Literacy Project","category":"Governance","description":"Leaked internal documents detail 7-point strategy to challenge scientific consensus bodies. Targets CDC vaccine advisory committee, EPA climate science, FDA drug review processes. Institutional damage extends beyond specific policies.","url":"https://geneticliteracyproject.org","published_date":SCAN_DATE,"steep_category":"P","tags":["US policy","science governance","CDC","FDA","EPA","institutional trust"],"relevance_score":7.5},
]

output = {
    "scan_metadata": {
        "scan_date": SCAN_DATE,
        "source": "InvestScan ENV injector — 2026-05-08 integrated report",
        "total_signals": len(signals),
        "workflows": ["WF1","WF2","WF3","WF4"],
        "generated_at": datetime.now().isoformat(),
        "note": "Injected from integrated-scan-2026-05-08.md (727 signals → Top 20 selected)"
    },
    "items": signals
}

DEST.write_text(json.dumps(output, ensure_ascii=False, indent=2))
print(f"✅ {DEST} 생성 완료 ({len(signals)}개 신호)")
